version: "3"
services:
  frontend:
    container_name: stad-antwerpen-frontend
    build: ./frontend
    depends_on:
      - backend
    env_file: .env
    ports:
      - "8080:8080"  # Expose frontend directly on port 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stad-frontend.rule=Host(`${HOSTNAME}`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.stad-frontend.entrypoints=websecure"
      - "traefik.http.routers.stad-frontend.tls=true"
      - "traefik.http.routers.stad-frontend.tls.certresolver=letsencrypt"

  backend:
    container_name: stad-antwerpen-backend
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"  # Expose backend directly on port 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stad-backend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.stad-backend.entrypoints=websecure"
      - "traefik.http.routers.stad-backend.tls=true"
      - "traefik.http.routers.stad-backend.tls.certresolver=letsencrypt"
networks:
  traefik:
    external: true

services:
  frontend:
    networks:
      - traefik
  backend:
    networks:
      - traefik
